import type { Dispute, Order, Product, Vehicle } from "@partsloop/contracts";

export const garage: Vehicle[] = [
  { id: "veh_lc", make: "Toyota", model: "Land Cruiser", year: 2021, engine: "4.0L V6", trim: "GXR" },
  { id: "veh_patrol", make: "Nissan", model: "Patrol", year: 2019, engine: "5.6L V8", trim: "Platinum" },
];

export const products: Product[] = [
  {
    id: "prd_headlight",
    slug: "toyota-land-cruiser-led-headlight-81150-60r30",
    title: "Toyota Land Cruiser LED Headlight — Left",
    titleAr: "مصباح ليد يسار تويوتا لاند كروزر",
    description: "Genuine OEM left headlight removed from a low-mileage donor vehicle. Lens is clear, mounting tabs are intact, and the light has been bench tested.",
    descriptionAr: "مصباح أمامي أصلي يسار من سيارة قليلة الاستخدام. العدسة صافية وقواعد التثبيت سليمة وتم اختبار المصباح.",
    category: "Lights",
    oemNumber: "81150-60R30",
    price: { amount: 850, currency: "AED" },
    condition: "used",
    grade: "a",
    compatibility: "confirmed",
    compatibleVehicles: ["Toyota Land Cruiser 2018–2021 4.0L V6 Petrol GXR VXR", "Lexus LX 2018–2021 5.7L V8 Petrol"],
    seller: { id: "sel_1", name: "Al Quoz Auto Parts", city: "Dubai", verified: true, rating: 4.9, completedOrders: 1264, responseMinutes: 8 },
    deliveryLabel: "Delivery tomorrow",
    warrantyDays: 30,
    visual: "headlight",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/LED_Headlamp_inside.jpg",
    imageAlt: "Close view inside an automotive LED headlamp assembly",
    defects: ["Two faint surface marks"],
    featured: true,
  },
  {
    id: "prd_engine",
    slug: "nissan-patrol-vk56-engine",
    title: "Nissan Patrol VK56 5.6L Engine",
    titleAr: "محرك نيسان باترول VK56 سعة 5.6 لتر",
    description: "Tested complete engine with compression report. Donor mileage 78,400 km.",
    descriptionAr: "محرك كامل ومختبر مع تقرير ضغط. ممشى السيارة المانحة 78,400 كم.",
    category: "Engines",
    oemNumber: "VK56VD",
    price: { amount: 12800, currency: "AED" },
    condition: "used",
    grade: "b",
    compatibility: "possible",
    compatibleVehicles: ["Nissan Patrol Y62 2017–2021 5.6L V8 Petrol SE LE"],
    seller: { id: "sel_2", name: "Sharjah Motor Hub", city: "Sharjah", verified: true, rating: 4.8, completedOrders: 842, responseMinutes: 14 },
    deliveryLabel: "2–3 business days",
    warrantyDays: 14,
    visual: "engine",
    imageUrl: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "Automotive engine being inspected in a workshop",
    defects: ["Cosmetic oxidation on cover"],
    featured: true,
  },
  {
    id: "prd_mirror",
    slug: "lexus-lx570-right-mirror",
    title: "Lexus LX570 Right Mirror with Camera",
    titleAr: "مرآة يمين لكزس LX570 مع كاميرا",
    description: "Power-folding mirror assembly with camera and indicator. Pearl white cap included.",
    descriptionAr: "مرآة كهربائية قابلة للطي مع كاميرا وإشارة. الغطاء الأبيض اللؤلؤي مشمول.",
    category: "Body",
    oemNumber: "87910-60D80",
    price: { amount: 1190, currency: "AED" },
    condition: "refurbished",
    grade: "a",
    compatibility: "confirmed",
    compatibleVehicles: ["Lexus LX 570 2016–2021 5.7L V8 Petrol Premier Platinum"],
    seller: { id: "sel_1", name: "Al Quoz Auto Parts", city: "Dubai", verified: true, rating: 4.9, completedOrders: 1264, responseMinutes: 8 },
    deliveryLabel: "Delivery tomorrow",
    warrantyDays: 60,
    visual: "mirror",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "Premium vehicle detail suitable for a mirror assembly listing",
    defects: [],
  },
  {
    id: "prd_gearbox",
    slug: "toyota-prado-automatic-gearbox",
    title: "Toyota Prado Automatic Gearbox 6-Speed",
    titleAr: "جير أوتوماتيك تويوتا برادو 6 سرعات",
    description: "Bench-tested transmission, flushed and supplied with a fitting kit.",
    descriptionAr: "ناقل حركة تم اختباره وتنظيفه ويأتي مع طقم تركيب.",
    category: "Transmission",
    oemNumber: "35010-35B70",
    price: { amount: 4950, currency: "AED" },
    condition: "refurbished",
    grade: "a",
    compatibility: "confirmed",
    compatibleVehicles: ["Toyota Prado 2018–2022 4.0L V6 Petrol GXR VXR"],
    seller: { id: "sel_3", name: "Gulf Gearbox Centre", city: "Abu Dhabi", verified: true, rating: 4.7, completedOrders: 411, responseMinutes: 21 },
    deliveryLabel: "2 business days",
    warrantyDays: 90,
    visual: "gearbox",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/Gearbox.jpg",
    imageAlt: "Detailed automotive gearbox assembly",
    defects: [],
  },
  {
    id: "prd_wheel",
    slug: "range-rover-sport-22-wheel",
    title: "Range Rover Sport 22-inch Alloy Wheel",
    titleAr: "رنج روفر سبورت جنط ألمنيوم 22 بوصة",
    description: "Single genuine alloy wheel, inspected for bends and cracks.",
    descriptionAr: "جنط ألمنيوم أصلي مفرد، تم فحصه من الاعوجاج والتشققات.",
    category: "Wheels",
    oemNumber: "LR099138",
    price: { amount: 975, currency: "AED" },
    condition: "used",
    grade: "b",
    compatibility: "unverified",
    compatibleVehicles: ["Land Rover Range Rover Sport 2018–2022 3.0L I6 Petrol HSE"],
    seller: { id: "sel_4", name: "Desert Wheels", city: "Dubai", verified: false, rating: 4.5, completedOrders: 98, responseMinutes: 35 },
    deliveryLabel: "Delivery in 2 days",
    warrantyDays: 7,
    visual: "wheel",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Alumwheel.jpg",
    imageAlt: "Aluminium alloy automotive wheel",
    defects: ["Light kerb mark"],
  },
  {
    id: "prd_bumper",
    slug: "hyundai-tucson-front-bumper",
    title: "Hyundai Tucson Front Bumper — Primed",
    titleAr: "صدام أمامي هيونداي توسان جاهز للصبغ",
    description: "New aftermarket bumper cover supplied primed and ready for paint.",
    descriptionAr: "غطاء صدام تجاري جديد جاهز للصبغ.",
    category: "Body",
    oemNumber: "86511-N9000",
    price: { amount: 430, currency: "AED" },
    condition: "new",
    grade: "new",
    compatibility: "confirmed",
    compatibleVehicles: ["Hyundai Tucson 2021–2024 2.0L I4 Petrol Comfort Premium"],
    seller: { id: "sel_5", name: "Emirates New Parts", city: "Ajman", verified: true, rating: 4.8, completedOrders: 2083, responseMinutes: 6 },
    deliveryLabel: "Delivery tomorrow",
    warrantyDays: 180,
    visual: "bumper",
    imageUrl: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "Vehicle front bodywork in a professional workshop",
    defects: [],
  },
  {
    id: "prd_suspension",
    slug: "toyota-land-cruiser-front-coilover",
    title: "Toyota Land Cruiser Front Coilover Assembly",
    titleAr: "مساعد أمامي كامل تويوتا لاند كروزر",
    description: "Complete front coilover assembly with spring and top mount. Leak-tested, measured, and supplied with an inspection report.",
    descriptionAr: "مساعد أمامي كامل مع النابض والقاعدة العلوية، تم فحص التسريب والقياس ويأتي مع تقرير فحص.",
    category: "Suspension",
    oemNumber: "48510-60A80",
    price: { amount: 720, currency: "AED" },
    condition: "refurbished",
    grade: "a",
    compatibility: "confirmed",
    compatibleVehicles: ["Toyota Land Cruiser 2016–2021 4.6L V8 Petrol GXR VXR", "Lexus LX 570 2016–2021 5.7L V8 Petrol"],
    seller: { id: "sel_6", name: "Gulf Chassis Lab", city: "Dubai", verified: true, rating: 4.9, completedOrders: 676, responseMinutes: 9 },
    deliveryLabel: "Delivery tomorrow",
    warrantyDays: 60,
    visual: "suspension",
    imageUrl: "/partsloop-precision-3d.png",
    imageAlt: "Precision-rendered automotive coilover suspension assembly",
    defects: [],
    featured: true,
  },
  {
    id: "prd_ecu",
    slug: "nissan-patrol-engine-control-module",
    title: "Nissan Patrol Engine Control Module — ECU",
    titleAr: "كمبيوتر محرك نيسان باترول ECU",
    description: "Original engine control module, bench tested and supplied unlocked for professional VIN coding.",
    descriptionAr: "كمبيوتر محرك أصلي تم اختباره ويأتي مفتوحاً للبرمجة المهنية على رقم الهيكل.",
    category: "Electrical & Electronics",
    oemNumber: "23710-5ZW0A",
    price: { amount: 1650, currency: "AED" },
    condition: "refurbished",
    grade: "a",
    compatibility: "confirmed",
    compatibleVehicles: ["Nissan Patrol Y62 2020–2024 5.6L V8 Petrol LE Platinum"],
    seller: { id: "sel_7", name: "Emirates ECU Lab", city: "Sharjah", verified: true, rating: 4.9, completedOrders: 923, responseMinutes: 5 },
    deliveryLabel: "Same-day dispatch",
    warrantyDays: 90,
    visual: "electronics",
    imageUrl: "/partsloop-precision-3d.png",
    imageAlt: "Precision-rendered automotive electronic control module",
    defects: [],
    featured: true,
  },
  {
    id: "prd_brakes",
    slug: "lexus-lx570-front-brake-kit",
    title: "Lexus LX570 Front Brake Disc & Caliper Kit",
    titleAr: "طقم ديسك وكليبر أمامي لكزس LX570",
    description: "Matched front brake set with measured disc thickness, pressure-tested calipers, and fitting hardware.",
    descriptionAr: "طقم فرامل أمامي متطابق مع قياس سماكة الأقراص واختبار ضغط الكليبر وملحقات التركيب.",
    category: "Brakes",
    oemNumber: "43512-60180",
    price: { amount: 1380, currency: "AED" },
    condition: "refurbished",
    grade: "a",
    compatibility: "confirmed",
    compatibleVehicles: ["Lexus LX 570 2016–2021 5.7L V8 Petrol Premier Platinum", "Toyota Land Cruiser 2016–2021 5.7L V8 Petrol VXR"],
    seller: { id: "sel_8", name: "Precision Brake Works", city: "Abu Dhabi", verified: true, rating: 4.8, completedOrders: 518, responseMinutes: 12 },
    deliveryLabel: "Delivery in 2 days",
    warrantyDays: 45,
    visual: "brakes",
    imageUrl: "/partsloop-precision-3d.png",
    imageAlt: "Precision-rendered ventilated brake disc and caliper",
    defects: [],
    featured: true,
  },
  {
    id: "prd_turbo",
    slug: "toyota-land-cruiser-twin-turbocharger",
    title: "Toyota Land Cruiser 3.3D Turbocharger",
    titleAr: "تيربو تويوتا لاند كروزر 3.3 ديزل",
    description: "Remanufactured turbocharger with balanced core, actuator calibration sheet, and installation gasket set.",
    descriptionAr: "تيربو مجدد بقلب موزون وتقرير معايرة للمشغل وطقم جوانات للتركيب.",
    category: "Engines",
    oemNumber: "17201-0W090",
    price: { amount: 2950, currency: "AED" },
    condition: "refurbished",
    grade: "a",
    compatibility: "possible",
    compatibleVehicles: ["Toyota Land Cruiser 300 2022–2026 3.3L V6 Diesel GXR VXR"],
    seller: { id: "sel_9", name: "Dubai Turbo Centre", city: "Dubai", verified: true, rating: 4.8, completedOrders: 355, responseMinutes: 10 },
    deliveryLabel: "Delivery tomorrow",
    warrantyDays: 180,
    visual: "turbo",
    imageUrl: "/partsloop-precision-3d.png",
    imageAlt: "Precision-rendered automotive turbocharger",
    defects: [],
    featured: true,
  },
];

const trackedProduct = products[0];
export const orders: Order[] = [
  {
    id: "ord_1",
    publicId: "PL-10482",
    product: trackedProduct,
    quantity: 1,
    subtotal: trackedProduct.price,
    delivery: { amount: 35, currency: "AED" },
    serviceFee: { amount: 20, currency: "AED" },
    total: { amount: 905, currency: "AED" },
    status: "inspection",
    paymentIntentId: "mock_pi_10482",
    trackingNumber: "MOCK-AE-884201",
    inspectionEndsAt: "2026-07-28T18:00:00.000Z",
    events: [
      { status: "payment_secured", label: "Payment secured", labelAr: "تم تأمين الدفع", at: "26 Jul, 10:15", complete: true },
      { status: "seller_confirmed", label: "Seller confirmed", labelAr: "أكد البائع", at: "26 Jul, 10:22", complete: true },
      { status: "packed", label: "Part packed", labelAr: "تم تجهيز القطعة", at: "26 Jul, 13:05", complete: true },
      { status: "collected", label: "Courier collected", labelAr: "استلمت شركة الشحن", at: "26 Jul, 16:40", complete: true },
      { status: "delivered", label: "Delivered", labelAr: "تم التوصيل", at: "27 Jul, 11:20", complete: true },
      { status: "inspection", label: "48-hour inspection", labelAr: "فترة فحص 48 ساعة", complete: false, current: true },
      { status: "released", label: "Seller payout", labelAr: "تحويل المبلغ للبائع", complete: false },
    ],
  },
];

export const disputes: Dispute[] = [
  {
    id: "dsp_1",
    orderId: "PL-10482",
    reason: "does_not_fit",
    buyerStatement: "The connector has six pins but my vehicle harness has eight. The workshop confirmed it cannot be fitted.",
    sellerStatement: "The listing states Prado 2018–2022. Please verify the buyer trim and share the VIN.",
    status: "under_review",
    amount: { amount: 905, currency: "AED" },
    evidence: [
      { label: "Buyer connector photo", type: "photo" },
      { label: "OEM label photo", type: "photo" },
      { label: "Workshop inspection note", type: "document" },
    ],
    recommendedResolution: "refund",
  },
];

export function findProduct(idOrSlug: string) {
  return products.find((product) => product.id === idOrSlug || product.slug === idOrSlug);
}
